### ISSUE TITLE
[wish] image flipping

### ISSUE THREAD

**Issue by retokromer** [ietf-wg-cellar/matroska-specification#330] opened 2019-07-22 16:45 UTC
As [requested](https://github.com/cellar-wg/matroska-specification/pull/326#issuecomment-513852464) by @dericed:

I suggest to add the handling of specular images (vertical and/or horizontal flipping). For the people implementing Matroska into players it’s of the same family than rotation.

**Context:** One film reel can be digitised emulsion to sensor or base to sensor, from platter A to platter B or from platter B to platter A, and there are four combinations for the rotation of the platters. In case of highly damaged films, it’s actually the film itself who decides which configuration is chosen, not the operating person (no joke!). It’s useful when the raw scan can be played correctly without having to modify the player’s parameters.

**Comment by robUx4** [comment] 2019-07-23 18:53
As said in #326 I think `ProjectionPoseYaw` and `ProjectionPosePitch` can be used for horizontal and vertical flipping respectively. We just need to document the special case of 180 degree for each.

**Comment by robUx4** [comment] 2021-04-04 13:10
Duplicate of #326

**Closed by robUx4** 2021-04-04 13:10 UTC
Labels: clarifications, format addition, spec_main
